trailingComma: "es5"
tabWidth: 2
semi: true
singleQuote: true
printWidth: 120
overrides:
  - files: "*.yml"
    options:
      tabWidth: 2
      printWidth: 80
  - files: '*.md'
    options:
      tabWidth: 2
      printWidth: 80
